### ISSUE TITLE
Can not get it working

### ISSUE THREAD

**Issue by dajor** [phrase/ember-cli-phraseapp#4]
So i am new in ember and may be i do something wrong here:

So I start

ember new demoapp
ember g route test
vi app/templates/test.hbs 
just add test

http://localhost:4200/test works

npm install ember-cli-i18n --save-dev
now it test does not show anything up but let add the other config

vi config/environment.js

```
var ENV = {
  APP: {
    defaultLocale: 'en'
  }
};
```

ember g locale en

vi app/locales/en.js

```
export default {
  home: {
    title: 'Welcome'
  }
};
```

vi app/templates/test.hbs 

Add {{t 'home.title'}}

http://localhost:4200/test is empty

**Comment by sacry-dyn** [comment]
Hi,

we are looking into it and come back to you if we find anything.

Regards,
Matthias

**Comment by sacry-dyn** [comment]
@dajor So we set it up normally with the following:

```
ember install ember-i18n # (ember-cli-i18n is deprecated by now)
ember new demoapp
ember generate locale en 
# the file structure is different
# en is found under app/locales/en/translations.js
ember server
```

After that when I reference the keys defined in `translations.js` they work normally.

Regards,
Matthias

**Comment by dajor** [comment]
Hi Matthias,

thanks for your comment. When i try to install i go now a new error 

ember install ember-i18n
WARNING: Node v7.4.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
WARNING: Skipping npm install: package.json not found
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Class.run (/usr/local/lib/node_modules/ember-cli/lib/tasks/addon-install.js:43:7)
    at Class.run (/usr/local/lib/node_modules/ember-cli/lib/commands/install.js:39:25)
    at Class.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/models/command.js:241:20)
    at initializePromise (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:588:5)
    at PromiseExt.Promise (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1076:31)
    at new PromiseExt (/usr/local/lib/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.validateAndRun (/usr/local/lib/node_modules/ember-cli/lib/models/command.js:195:12)
    at /usr/local/lib/node_modules/ember-cli/lib/cli/cli.js:130:22
    at tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)

**Comment by dajor** [comment]
Hi,

it works. 

ember new demoapp
ember install ember-i18n
ember generate locale en 


app/locales/en/translations.js
